{
 "title": "Bandwidth Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Combined Upload Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(bandwidth.upload.*)"
    }
   ]
  },
  {
   "title": "Combined Download Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(bandwidth.download.*)"
    }
   ]
  },
  {
   "title": "Combined Upload/Download - Bi-Directional",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "bandwidth.download.*" },
    { "target": "bandwidth.upload.*" }
   ]
  },
  {
   "title": "Bandwidth Download",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(bandwidth.download.*)"
    }
   ]
  },
  {
   "title": "Bandwidth Upload",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "averageSeries(bandwidth.upload.*)"
    }
   ]
  },
  {
   "title": "Digital Ocean Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "bandwidth.download.digitalocean"
    },
    { "target": "bandwidth.upload.digitalocean" }
   ]
  },
  {
   "title": "Test VirtualBox Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.virtualbox" },
    { "target": "bandwidth.upload.virtualbox" }
   ]
  },
  {
   "title": "Microsoft Azure Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.azure" },
    { "target": "bandwidth.upload.azure" }
   ]
  },
  {
   "title": "RackSpace Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.rackspace" },
    { "target": "bandwidth.upload.rackspace" }
   ]
  },
  {
   "title": "Google Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "bandwidth.download.google" },
    { "target": "bandwidth.upload.google" }
   ]
  },
  {
   "title": "IBM Softlayer Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.softlayer" },
    { "target": "bandwidth.upload.softlayer" }
   ]
  },
  {
   "title": "VMware Fusion Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "bandwidth.download.vmwarefusion"
    },
    { "target": "bandwidth.upload.vmwarefusion" }
   ]
  },
  {
   "title": "Amazon EC2 Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.amazonec2" },
    { "target": "bandwidth.upload.amazonec2" }
   ]
  },
  {
   "title": "VMware vSphere",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "bandwidth.download.vmwarevsphere"
    },
    { "target": "bandwidth.upload.vmwarevsphere" }
   ]
  },
  {
   "title": "Upload on Top / Download on Bottom",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "target": "aliasByMetric(scale(bandwidth.download.*, -1))"
    },
    {
     "target": "aliasByMetric(bandwidth.upload.*)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "target": "aliasByMetric(scale(bandwidth.download.*, -1))"
    },
    {
     "target": "aliasByMetric(bandwidth.upload.*)"
    }
   ]
  }
 ]
}