{
 "title": "Bandwidth Distributed Performance Server Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Combined Upload Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(bandwidth.upload.*)"
    }
   ]
  },
  {
   "title": "Combined Download Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(bandwidth.download.*)"
    }
   ]
  },
  {
   "title": "Combined Upload/Download - Bi-Directional",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "bandwidth.download.*" },
    { "target": "bandwidth.upload.*" }
   ]
  },
  {
   "title": "Average Download Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "averageSeries(bandwidth.download.*)"
    }
   ]
  },
  {
   "title": "Average Upload Bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "averageSeries(bandwidth.upload.*)"
    }
   ]
  },
  {
   "title": "Cluster-A Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "bandwidth.download.cluster-a" },
    { "target": "bandwidth.upload.cluster-a" }
   ]
  },
  {
   "title": "Cluster-B Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.cluster-b" },
    { "target": "bandwidth.upload.cluster-b" }
   ]
  },
  {
   "title": "Cluster-C Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.cluster-c" },
    { "target": "bandwidth.upload.cluster-c" }
   ]
  },
  {
   "title": "Cluster-D Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.download.cluster-d" },
    { "target": "bandwidth.upload.cluster-d" }
   ]
  }
 ]
}