{
 "title": "Bandwidth Aggregate Netperf Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Aggregate Node Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "sumSeries(bandwidth.netperf.*)" }
   ]
  },
  {
   "title": "Current Aggregated Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "sumSeries(bandwidth.netperf.*)" }
   ]
  },
  {
   "title": "All Nodes NetPerf Bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(bandwidth.netperf.*)"
    }
   ]
  },
  {
   "title": "Node-A Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "bandwidth.netperf.cluster-a" }
   ]
  },
  {
   "title": "Node-B Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.netperf.cluster-b" }
   ]
  },
  {
   "title": "Node-C Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.netperf.cluster-c" }
   ]
  },
  {
   "title": "Node-D Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "target": "bandwidth.netperf.cluster-d" }
   ]
  }
 ]
}